import { FilterCategory, Job } from "@/types/Job/jobTypes";

export const jobData: Job[] = [
  {
    id: "JOB_1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p",
    title: "Mobile Application Developer (iOS), App Store",
    company: "Apple",
    logo: "ic:sharp-apple",
    location: "Cupertino, California",
    type: "FULLTIME",
    yoe: "3+ years",
    salary: "35LPA",
    posted: "3 days ago",
    applications: 120,
    skills: [
      "Swift",
      "UIKit",
      "Core Data",
      "SwiftUI",
      "Combine",
      "Core Animation",
      "XCTest",
      "App Store Connect",
    ],
    description:
      "Join Apple's App Store team to develop innovative iOS applications used by millions worldwide. You'll work with cutting-edge technologies to create seamless user experiences while adhering to Apple's strict quality guidelines. Collaborate with cross-functional teams to bring new features to life on Apple's ecosystem.",
  },
  {
    id: "JOB_2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q",
    title: "Senior Frontend Engineer - React",
    company: "Google",
    logo: "devicon:google",
    location: "Mountain View, California",
    type: "FULLTIME",
    yoe: "5+ years",
    salary: "42LPA",
    posted: "1 day ago",
    applications: 85,
    skills: [
      "React",
      "TypeScript",
      "GraphQL",
      "Next.js",
      "Redux",
      "Jest",
      "Webpack",
      "CSS-in-JS",
    ],
    description:
      "Lead the development of Google's next-generation web applications using React and modern frontend technologies. You'll architect scalable solutions that handle millions of users while maintaining performance and accessibility standards. Mentor junior engineers and collaborate with UX designers to create intuitive interfaces for Google's diverse product portfolio.",
  },
  {
    id: "JOB_3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r",
    title: "DevOps Engineer",
    company: "Amazon",
    logo: "ri:amazon-fill",
    location: "Seattle, Washington",
    type: "FULLTIME",
    yoe: "4+ years",
    salary: "38LPA",
    posted: "5 days ago",
    applications: 64,
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "Prometheus",
      "Ansible",
      "Linux Administration",
    ],
    description:
      "Build and maintain Amazon's cloud infrastructure to support our global e-commerce platform. Implement CI/CD pipelines that enable rapid deployment while ensuring system reliability and security. Optimize resource utilization and automate operational processes to handle peak traffic during major sales events.",
  },
  {
    id: "JOB_4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s",
    title: "UX Designer",
    company: "Microsoft",
    logo: "logos:microsoft-icon",
    location: "Redmond, Washington",
    type: "CONTRACT",
    yoe: "2+ years",
    salary: "28LPA",
    posted: "1 week ago",
    applications: 42,
    skills: [
      "Figma",
      "Sketch",
      "User Research",
      "Prototyping",
      "User Testing",
      "Information Architecture",
      "Accessibility",
      "Fluent Design System",
    ],
    description:
      "Design user experiences for Microsoft's enterprise software solutions that empower businesses worldwide. Conduct user research to understand pain points and create intuitive interfaces that enhance productivity. Collaborate with product managers and engineers to translate business requirements into elegant design solutions that follow Fluent Design System principles.",
  },
  {
    id: "JOB_5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t",
    title: "Data Scientist",
    company: "Netflix",
    logo: "ri:netflix-fill",
    location: "Los Gatos, California",
    type: "FULLTIME",
    yoe: "3+ years",
    salary: "45LPA",
    posted: "2 days ago",
    applications: 93,
    skills: [
      "Python",
      "TensorFlow",
      "SQL",
      "PyTorch",
      "Pandas",
      "Spark",
      "A/B Testing",
      "Recommendation Systems",
    ],
    description:
      "Develop machine learning models that power Netflix's recommendation system and content personalization. Analyze vast datasets to uncover insights that drive business decisions and improve user engagement. Work closely with content teams to predict viewer preferences and optimize the streaming experience for millions of subscribers worldwide.",
  },
  {
    id: "JOB_6f7g8h9i-0j1k-2l3m-4n5o-6p7q8r9s0t1u",
    title: "Backend Engineer - Node.js",
    company: "Uber",
    logo: "hugeicons:uber",
    location: "San Francisco, California",
    type: "FULLTIME",
    yoe: "4+ years",
    salary: "40LPA",
    posted: "4 days ago",
    applications: 57,
    skills: [
      "Node.js",
      "MongoDB",
      "Redis",
      "Express",
      "GraphQL",
      "Microservices",
      "WebSockets",
      "Performance Optimization",
    ],
    description:
      "Build and scale the backend systems that power Uber's global transportation platform. Develop high-performance APIs that handle millions of real-time ride requests and driver allocations. Ensure system reliability through robust architecture and participate in on-call rotations to maintain 99.99% uptime for critical services.",
  },
  {
    id: "JOB_7g8h9i0j-1k2l-3m4n-5o6p-7q8r9s0t1u2v",
    title: "Product Manager",
    company: "Tesla",
    logo: "ri:tesla-fill",
    location: "Palo Alto, California",
    type: "FULLTIME",
    yoe: "6+ years",
    salary: "50LPA",
    posted: "1 day ago",
    applications: 38,
    skills: [
      "Product Strategy",
      "Agile",
      "Roadmapping",
      "User Stories",
      "Market Research",
      "KPI Tracking",
      "Stakeholder Management",
      "Go-to-Market",
    ],
    description:
      "Lead product development for Tesla's cutting-edge electric vehicles and energy solutions. Define product requirements by analyzing market trends and customer feedback to maintain Tesla's innovation leadership. Coordinate cross-functional teams including engineering, design, and manufacturing to deliver products that accelerate the world's transition to sustainable energy.",
  },
  {
    id: "JOB_8h9i0j1k-2l3m-4n5o-6p7q-8r9s0t1u2v3w",
    title: "QA Automation Engineer",
    company: "Adobe",
    logo: "logos:adobe-icon",
    location: "San Jose, California",
    type: "FULLTIME",
    yoe: "3+ years",
    salary: "32LPA",
    posted: "1 week ago",
    applications: 29,
    skills: [
      "Selenium",
      "JUnit",
      "TestNG",
      "Cypress",
      "Postman",
      "Load Testing",
      "Test Planning",
      "Defect Tracking",
    ],
    description:
      "Ensure the quality of Adobe's creative software suite through comprehensive test automation. Design and implement automated test frameworks that validate functionality across multiple platforms and devices. Collaborate with development teams to identify edge cases and prevent regressions in Photoshop, Illustrator, and other professional creative tools.",
  },
  {
    id: "JOB_9i0j1k2l-3m4n-5o6p-7q8r-9s0t1u2v3w4x",
    title: "Cloud Architect",
    company: "IBM",
    logo: "ri:ibm-fill",
    location: "Armonk, New York",
    type: "FULLTIME",
    yoe: "8+ years",
    salary: "55LPA",
    posted: "3 days ago",
    applications: 21,
    skills: [
      "Azure",
      "Terraform",
      "CI/CD",
      "Cloud Security",
      "Serverless",
      "Kubernetes",
      "Cost Optimization",
      "Multi-cloud",
    ],
    description:
      "Design and implement enterprise cloud solutions for IBM's global clients across various industries. Develop cloud migration strategies that optimize performance, security, and cost-efficiency for mission-critical workloads. Lead technical teams in adopting cloud-native architectures and serve as a trusted advisor to C-level executives on digital transformation initiatives.",
  },
  {
    id: "JOB_0j1k2l3m-4n5o-6p7q-8r9s-0t1u2v3w4x5y",
    title: "Technical Writer",
    company: "GitHub",
    logo: "ri:github-fill",
    location: "Remote",
    type: "PARTTIME",
    yoe: "2+ years",
    salary: "25LPA",
    posted: "2 weeks ago",
    applications: 47,
    skills: [
      "Documentation",
      "Markdown",
      "API Guides",
      "Technical Editing",
      "Developer Portals",
      "OpenAPI/Swagger",
      "Version Control",
      "User Personas",
    ],
    description:
      "Create clear, comprehensive documentation that helps developers master GitHub's platform and tools. Translate complex technical concepts into accessible tutorials, API references, and best practice guides. Collaborate with product teams to ensure documentation stays current with new features and improvements in the GitHub ecosystem.",
  },
  {
    id: "JOB_1k2l3m4n-5o6p-7q8r-9s0t-1u2v3w4x5y6z",
    title: "Security Engineer",
    company: "Cisco",
    logo: "ri:cisco-fill",
    location: "San Jose, California",
    type: "FULLTIME",
    yoe: "5+ years",
    salary: "48LPA",
    posted: "5 days ago",
    applications: 33,
    skills: [
      "Pen Testing",
      "SIEM",
      "Firewalls",
      "Threat Modeling",
      "OWASP",
      "Incident Response",
      "Cryptography",
      "Network Security",
    ],
    description:
      "Protect Cisco's networking infrastructure and customer data from evolving cyber threats. Conduct vulnerability assessments and penetration tests to identify security weaknesses in hardware and software systems. Develop security protocols and educate engineering teams on secure coding practices to maintain Cisco's reputation as a trusted technology provider.",
  },
  {
    id: "JOB_2l3m4n5o-6p7q-8r9s-0t1u-2v3w4x5y6z7a",
    title: "AI Research Scientist",
    company: "OpenAI",
    logo: "ri:openai-fill",
    location: "San Francisco, California",
    type: "FULLTIME",
    yoe: "PhD + 2 years",
    salary: "60LPA",
    posted: "1 day ago",
    applications: 18,
    skills: [
      "ML",
      "PyTorch",
      "NLP",
      "Deep Learning",
      "Transformers",
      "Reinforcement Learning",
      "Computer Vision",
      "Research Publications",
    ],
    description:
      "Push the boundaries of artificial intelligence through groundbreaking research at OpenAI. Develop novel algorithms and models that advance the fields of natural language processing and machine learning. Publish findings in top-tier conferences and contribute to open-source projects that democratize access to AI technologies.",
  },
  {
    id: "JOB_3m4n5o6p-7q8r-9s0t-1u2v-3w4x5y6z7a8b",
    title: "Android Developer",
    company: "Samsung",
    logo: "ri:samsung-fill",
    location: "Seoul, South Korea",
    type: "FULLTIME",
    yoe: "3+ years",
    salary: "36LPA",
    posted: "1 week ago",
    applications: 52,
    skills: [
      "Kotlin",
      "Jetpack",
      "Android SDK",
      "Coroutines",
      "Dagger/Hilt",
      "MVVM",
      "Espresso",
      "Play Store Deployment",
    ],
    description:
      "Develop innovative Android applications for Samsung's flagship mobile devices and ecosystem. Optimize app performance to take full advantage of Samsung's hardware capabilities and custom Android implementations. Collaborate with global teams to create localized experiences for Samsung's diverse international customer base.",
  },
  {
    id: "JOB_4n5o6p7q-8r9s-0t1u-2v3w-4x5y6z7a8b9c",
    title: "Game Developer - Unity",
    company: "Electronic Arts",
    logo: "ri:ea-fill",
    location: "Redwood City, California",
    type: "CONTRACT",
    yoe: "3+ years",
    salary: "30LPA",
    posted: "2 days ago",
    applications: 41,
    skills: [
      "Unity",
      "C#",
      "3D Modeling",
      "Shader Programming",
      "Physics Simulation",
      "Multiplayer Networking",
      "Performance Optimization",
      "Asset Pipelines",
    ],
    description:
      "Create immersive gaming experiences for EA's portfolio of world-class video game titles. Develop gameplay mechanics, UI systems, and tools using Unity for cross-platform deployment. Work closely with artists and designers to bring creative visions to life while meeting technical requirements and performance targets.",
  },
  {
    id: "JOB_5o6p7q8r-9s0t-1u2v-3w4x-5y6z7a8b9c0d",
    title: "Database Administrator",
    company: "Oracle",
    logo: "ri:oracle-fill",
    location: "Austin, Texas",
    type: "FULLTIME",
    yoe: "4+ years",
    salary: "34LPA",
    posted: "3 weeks ago",
    applications: 27,
    skills: [
      "SQL",
      "NoSQL",
      "Performance Tuning",
      "Database Security",
      "Backup/Recovery",
      "Sharding",
      "Oracle DB",
      "Data Modeling",
    ],
    description:
      "Manage and optimize Oracle's enterprise database systems that power critical business applications. Implement high-availability solutions and disaster recovery plans to ensure data integrity and minimal downtime. Provide expert guidance on database schema design, query optimization, and migration strategies for Oracle's global client base.",
  },
  {
    id: "JOB_6p7q8r9s-0t1u-2v3w-4x5y-6z7a8b9c0d1e",
    title: "Technical Support Engineer",
    company: "Dell",
    logo: "ri:dell-fill",
    location: "Round Rock, Texas",
    type: "FULLTIME",
    yoe: "2+ years",
    salary: "22LPA",
    posted: "4 days ago",
    applications: 63,
    skills: [
      "Troubleshooting",
      "Linux",
      "Networking",
      "Hardware Diagnostics",
      "Customer Service",
      "Ticketing Systems",
      "Remote Support",
      "Documentation",
    ],
    description:
      "Provide expert technical support for Dell's enterprise hardware and software solutions. Diagnose and resolve complex issues reported by corporate clients and IT professionals. Document solutions in knowledge bases and work with engineering teams to identify recurring problems that require product improvements.",
  },
  {
    id: "JOB_7q8r9s0t-1u2v-3w4x-5y6z-7a8b9c0d1e2f",
    title: "Blockchain Developer",
    company: "Coinbase",
    logo: "ri:coinbase-fill",
    location: "Remote",
    type: "PARTTIME",
    yoe: "3+ years",
    salary: "50LPA",
    posted: "1 day ago",
    applications: 29,
    skills: [
      "Solidity",
      "Ethereum",
      "Smart Contracts",
      "Web3.js",
      "DeFi",
      "NFT Standards",
      "Cryptography",
      "Blockchain Security",
    ],
    description:
      "Build decentralized applications and smart contracts for Coinbase's cryptocurrency platform. Develop secure blockchain solutions that enable new financial products and services in the Web3 ecosystem. Stay current with emerging blockchain protocols and contribute to open-source projects that advance the cryptocurrency industry.",
  },
  {
    id: "JOB_8r9s0t1u-2v3w-4x5y-6z7a-8b9c0d1e2f3g",
    title: "AR/VR Developer",
    company: "Meta",
    logo: "ri:meta-fill",
    location: "Menlo Park, California",
    type: "FULLTIME",
    yoe: "3+ years",
    salary: "45LPA",
    posted: "1 week ago",
    applications: 36,
    skills: [
      "Unity",
      "ARKit",
      "3D Graphics",
      "Shader Programming",
      "Spatial Computing",
      "Oculus SDK",
      "Performance Optimization",
      "Physics Simulation",
    ],
    description:
      "Create immersive augmented and virtual reality experiences for Meta's metaverse initiatives. Develop interactive 3D environments and applications that push the boundaries of social interaction in virtual spaces. Optimize performance for Meta's VR hardware platforms while maintaining high visual fidelity and responsive user interfaces.",
  },
  {
    id: "JOB_9s0t1u2v-3w4x-5y6z-7a8b-9c0d1e2f3g4h",
    title: "Embedded Systems Engineer",
    company: "Intel",
    logo: "ri:intel-fill",
    location: "Santa Clara, California",
    type: "FULLTIME",
    yoe: "4+ years",
    salary: "38LPA",
    posted: "2 weeks ago",
    applications: 24,
    skills: [
      "C/C++",
      "RTOS",
      "Microcontrollers",
      "Device Drivers",
      "ARM Architecture",
      "FPGA",
      "Hardware Debugging",
      "Low-level Programming",
    ],
    description:
      "Design and optimize embedded systems for Intel's cutting-edge processors and IoT devices. Develop low-level firmware that maximizes hardware performance while meeting strict power efficiency requirements. Collaborate with silicon design teams to create reference implementations that showcase Intel's latest chip architectures.",
  },
  {
    id: "JOB_0t1u2v3w-4x5y-6z7a-8b9c-0d1e2f3g4h5i",
    title: "Digital Marketing Specialist",
    company: "Twitter",
    logo: "ri:twitter-fill",
    location: "San Francisco, California",
    type: "FULLTIME",
    yoe: "3+ years",
    salary: "28LPA",
    posted: "3 days ago",
    applications: 58,
    skills: [
      "SEO",
      "Google Ads",
      "Social Media",
      "Content Strategy",
      "Analytics",
      "Email Marketing",
      "Conversion Optimization",
      "A/B Testing",
    ],
    description:
      "Develop and execute digital marketing campaigns that grow Twitter's user base and engagement. Analyze performance metrics to optimize ad spend and maximize ROI across multiple channels. Create compelling content strategies that leverage Twitter's unique platform capabilities while aligning with broader brand objectives.",
  },
  {
    id: "JOB_1u2v3w4x-5y6z-7a8b-9c0d-1e2f3g4h5i6j",
    title: "IT Project Manager",
    company: "Accenture",
    logo: "ri:accenture-fill",
    location: "Chicago, Illinois",
    type: "FULLTIME",
    yoe: "5+ years",
    salary: "42LPA",
    posted: "1 day ago",
    applications: 19,
    skills: [
      "Agile",
      "Scrum",
      "Stakeholder Management",
      "Risk Management",
      "Budgeting",
      "JIRA",
      "Waterfall",
      "Vendor Management",
    ],
    description:
      "Lead complex IT transformation projects for Accenture's Fortune 500 clients across various industries. Manage cross-functional teams to deliver solutions on time and within budget while meeting quality standards. Serve as the primary liaison between technical teams and executive stakeholders to ensure alignment with business objectives.",
  },
];

export const filterMenuData: FilterCategory[] = [
  {
    heading: "Salary Ranges",
    filters: [
      { label: "₹0 - ₹5 LPA", value: "0-500000" },
      { label: "₹5 - ₹10 LPA", value: "500001-1000000" },
      { label: "₹10 - ₹20 LPA", value: "1000001-2000000" },
      { label: "₹20 - ₹30 LPA", value: "2000001-3000000" },
      { label: "₹30 LPA+", value: "3000001-plus" },
    ],
  },
  {
    heading: "Location",
    filters: [
      { label: "Remote", value: "remote" },
      { label: "Bengaluru", value: "bengaluru" },
      { label: "Mumbai", value: "mumbai" },
      { label: "Delhi NCR", value: "delhi-ncr" },
      { label: "Hyderabad", value: "hyderabad" },
      { label: "Pune", value: "pune" },
      { label: "Chennai", value: "chennai" },
    ],
  },
  {
    heading: "Experience",
    filters: [
      { label: "Fresher", value: "fresher" },
      { label: "1-3 Years", value: "1-3-years" },
      { label: "3-5 Years", value: "3-5-years" },
      { label: "5-10 Years", value: "5-10-years" },
      { label: "10+ Years", value: "10-plus-years" },
    ],
  },
  {
    heading: "Job Type",
    filters: [
      { label: "Fulltime", value: "fulltime" },
      { label: "Part-time", value: "parttime" },
      { label: "Contract", value: "contract" },
      { label: "Internship", value: "internship" },
      { label: "Freelance", value: "freelance" },
    ],
  },
  {
    heading: "Work Mode",
    filters: [
      { label: "Remote", value: "remote" },
      { label: "On-site", value: "onsite" },
      { label: "Hybrid", value: "hybrid" },
    ],
  },
  {
    heading: "Department",
    filters: [
      { label: "Engineering", value: "engineering" },
      { label: "Product Management", value: "product-management" },
      { label: "Marketing", value: "marketing" },
      { label: "Sales", value: "sales" },
      { label: "Human Resources", value: "hr" },
      { label: "Design", value: "design" },
      { label: "Finance", value: "finance" },
    ],
  },
  {
    heading: "Skills",
    filters: [
      { label: "JavaScript", value: "javascript" },
      { label: "Python", value: "python" },
      { label: "Java", value: "java" },
      { label: "React", value: "react" },
      { label: "Node.js", value: "nodejs" },
      { label: "SQL", value: "sql" },
      { label: "AWS", value: "aws" },
    ],
  },
  {
    heading: "Education",
    filters: [
      { label: "High School", value: "high-school" },
      { label: "Bachelor’s Degree", value: "bachelors" },
      { label: "Master’s Degree", value: "masters" },
      { label: "PhD", value: "phd" },
    ],
  },
];

